### ISSUE TITLE
Confine fact to the newly added cloud fact

### ISSUE THREAD

**Issue by TraGicCode** [keirans/azuremetadata#14]
Newer versions of puppet now have a cloud fact so you can easily determine if a node is in azure so we can perform fact confining.  Lets get this implemented!

**Comment by keirans** [comment]
Thanks a bunch for this, its appreciated.
Just replied to your message on slack, but dropping here for tracking.

For this change, can we do the following as well.
* Remove the class inclusion from the readme as you correctly pointed out, its actually not required as factsync will sync all in the environment, even if the classified node doesn't use any module classes.
* Update the readme to bump the version to 1.0.0 as this will be a breaking change for older facter users that don't have the cloud fact present. A comment in the readme that older facter users should continue to use 0.x release modules would be nice as well, I'll put them on life support for new API versions only to keep the users of those era versions happy.

Can you also provide me with the version of PE / Puppet / Facter you tested this on as well when you have a moment, just lets me have an idea of the environments people are using for when i do testing of my own.

Thanks again !

K

**Comment by keirans** [comment]
As discussed, until Puppet expose the cloud fact on both Windows and Linux OS versions, we'll hold off this change.

Currently it doesn't exist on Windows, only Linux.

Closing off until that happens.

Thanks again.

K
