### ISSUE TITLE
Doesn't return a value on Windows 2016

### ISSUE THREAD

**Issue by rrapelje** [keirans/azuremetadata#22]
I have a Windows 2016 VM provisioned from the Azure marketplace image.  After adding this module to my puppetfile and running puppet agent -t on my Windows 2016 agent, I can see all the az_metadata when viewing the console Node -> my node name -> facts tab.  All the azure metadata is in the console and appears correct.

When I start powershell or powershell ISE and  run command facter az_metadata the output is a blank line.  When I run facter then I get just the basic facts.  (I have rebooted the VM)

I can successfully run these commands to fetch the location:  
$VM = Invoke-RestMethod -Method GET -Uri http://169.254.169.254/metadata/instance/compute?api-version=2017-04-02 -Headers @{'Metadata'='True'}

$VM.location

**Comment by keirans** [comment]
Hey There,
Try running one of the following:

```
facter -p
```

or

```
puppet facts
```

From memory, Facter won't pull in facts from the Puppet environment when executed by itself unless you explicitly configure the module paths in Facter it's  self (think of Facter as a seperate application to Puppet, that is leveraged by Puppet).

Let me know how you go.

Cheers,

K

**Comment by keirans** [comment]
Closing this out. Suspect this has been resolved.
