### ISSUE TITLE
Error: Could not run: undefined method `debug_msg' for main:Object

### ISSUE THREAD

**Issue by pillarsdotnet** [keirans/azuremetadata#4]
I'm getting the following error because, apparently, the `debug_msg` function is not implemented in the version of facter I have available.  Could this be changed to `puts`?

```
Error: Could not run: Could not retrieve facts for REDACTEDFQDN: undefined method `debug_msg' for main:Object
```

**Comment by keirans** [comment]
Hey @pillarsdotnet ,
Thanks for raising this :)

Could you please give me some additional information about your setup, specifically:
- OS Versions you are using this module with
- Any Platform information that may be relevant (if not Linux x64 / Windows x64 )
- The Puppet version you are using and if you are using PE or Opensource
- The version of facter you are using

What i'll do is look to see if we can do is add some logic that will use puts on older versions of facter, and debug_msg() for current ones. This will keep things cleaner for all users of the module.

Thanks again for feeding this back.

K

**Comment by pillarsdotnet** [comment]
* **OS Versions:** Only tested on `AmazonLinux 2017` so far, but I have to be able to support any 64-bit Linux or Windows.
* **Relevant Info:** I'm not using a full puppet installation; only the gem-files on top of Travelling-Ruby  `2.2`.
* **Puppet version** Gem version `4.5.3`
* **Facter version** Gem version `2.4.6`

**Comment by keirans** [comment]
Brilliant, thanks for this.

I'll look to replicate this in the next day or so and get a fix in for you to test.

Thanks again,

K

**Comment by keirans** [comment]
Hey @pillarsdotnet ,
I've pushed a new branch of this repo. Think you can give it a test for me.

That debug_msg function doesn't exist anywhere so i've switched it to a warn and restructured the logic a little.

Let me know how your testing goes and I'll merge it into master and build a new module for the forge.

Branch is: 
- https://github.com/keirans/azuremetadata/tree/warning_changes

Thanks ! :)

**Comment by pillarsdotnet** [comment]
Taking a look...

**Comment by pillarsdotnet** [comment]
Works here; thanks @keirans.

**Comment by keirans** [comment]
Hey @pillarsdotnet , 
I've published the new version on the forge.

Thanks again for letting me know you are using it and when it has issues.

Cheers,

K
